version: 2
jobs:
  docker-image-amd64:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build -t ${DOCKER_USER}/peertube:latest-amd64 .
      - run:
          name: upload image to docker hub.
          command: |
            docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}
            docker push ${DOCKER_USER}/peertube:latest-amd64

  docker-image-arm64:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Activate qemu
          command: |
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
            wget https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0-1/qemu-aarch64-static
            chmod +x qemu-aarch64-static
      - run:
          name: Change Dockerfile
          command: |
            sed -i -e "s/alpine:/arm64v8\/alpine:/" Dockerfile
            sed -i -e "2i ADD qemu-aarch64-static /usr/bin" Dockerfile
      - run:
          name: build docker image
          command: |
            docker build -t ${DOCKER_USER}/peertube:latest-arm64 .
      - run:
          name: upload image to docker hub.
          command: |
            docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}
            docker push ${DOCKER_USER}/peertube:latest-arm64

  docker-manifest:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install manifest-tool
          command: |
            wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O /usr/bin/manifest-tool
            chmod +x /usr/bin/manifest-tool
      - run:
          name: Push manifest
          command: |
            docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}
            manifest-tool push from-spec manifest.yaml            
    
workflows:
  version: 2
  build:
    jobs:
      - docker-image-amd64
      - docker-image-arm64
      - docker-manifest:
          requires:
            - docker-image-amd64
            - docker-image-arm64
